#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# accueil:
   # path: /
   # controller: App\Conttroller\HomeController::index 

about:
    path: /about
    controller: App\Controller\HomeController::about

contact:
    path: /contact
    controller: App\Controller\HomeController::contact

default:
    path: /contact
    controller: App\Controller\DefaultController::default